spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:8848 #nacos的地址
  #        namespace: e0557daf-875c-468c-9f16-90c0c91c277f
  #        cluster-name: TEST
  #        metadata:
  #          instance: c
  #          version: v1.0
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 8005

rocketmq:
  name-server: 127.0.0.1:9876