spring:
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:8848 #nacos的地址
    sentinel:
      filter:
        enabled: false #关闭掉对Spring Mvc断点的保护
      transport:
        #port: 8720
        dashboard: localhost:8080
        port: 8720
        heartbeat-interval-ms: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 9006
#Ribbon实现属性配置方式
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#请求微服务实例时使用饥饿加载的方式
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center
#  http:
#    client:
#      enabled: true
logging:
  level:
    com.alibaba.content.feign.UserCenterFeignClient: debug #feign的日志配置需要接口就是debug级别
#属性配置
#feign:
#  client:
#    config:
#      user-center:
#        loggerLevel: full
#feign全局配置
feign:
  client:
    config:
      default:
        #拦截器传递token的配置
        requestInterceptors:
          - com.alibaba.content.interceptor.TokenRelayRequestIntecepor
#        loggerLevel: full

#让feign使用apache httpclient做请求工具，性能优化
#feign:
#  httpclient:
#    enabled: true
#    max-connections: 200 #feign的最大连接数
#    max-connections-per-route: 50 #单路径的最大连接数

management:
  endpoints:
    web:
      exposure:
        include: '*'
#整合rocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group #小坑，必须指定group

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600