spring:
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos的地址
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 9006